// Separate private-review entry. Not part of the production index.html bundle.
import { createRoot } from "react-dom/client";
import { Router, Route, Switch, Link, useLocation } from "wouter";
import { useHashLocation } from "wouter/use-hash-location";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "./lib/queryClient";
import { TooltipProvider } from "./components/ui/tooltip";
import { SurveyFlow } from "./pages/SurveyFlow";
import { JoinSurveyFlow } from "./pages/JoinSurveyFlow";
import { Report } from "./pages/Report";
import { CohortReportView } from "./components/CohortReportView";
import { DebriefingReportView } from "./components/DebriefingReportView";
import { JJLogo } from "./lib/logo";
import { Button } from "./components/ui/button";
import { SURVEY_ITEMS } from "@shared/surveyItems";
import { retainedAnswers } from "@shared/shortForm";
import { buildCohortReporting } from "@shared/cohortReporting";
import { buildDebriefingReport } from "@shared/debriefing/engine";
import { mixedRows, makeSyntheticResponse } from "../../script/syntheticShortForm";
import "./index.css";

const answers = Object.fromEntries(SURVEY_ITEMS.map((item, i) => [item.code, 1 + (i * 3) % 5]));
function Sample({ initial }: { initial: number }) {
  const [, navigate] = useLocation();
  return <Report items={retainedAnswers(answers, initial)} preMaturity={initial} postMaturity={4} change={2} onRestart={() => navigate("/")} />;
}
function Home() {
  const options = [
    ["/survey", "Try the individual survey", "Choose Distant or Exploring for 38 questions; choose levels 3–5 for the unchanged full survey."],
    ["/join/SHORTPREVIEW", "Try the group survey", "Includes the existing demographics and comment question, followed by the private short-form report."],
    ["/sample/distant", "Sample Distant report", "See the six selected pathways without completing the survey."],
    ["/sample/exploring", "Sample Exploring report", "The same private report format, selected from the opening response."],
    ["/sample/full", "Existing full report", "Check the unchanged full-report content alongside the new version."],
    ["/group", "Mixed church results", "Synthetic full and short cohorts, reported separately."],
    ["/small", "Small-group privacy check", "See how insufficient response counts are protected."],
    ["/debrief", "Admin debrief preview", "Full-survey analysis only, with separate short-form item results."],
    ["/join/GRACEDEMO", "Participant demo", "The existing non-saving demo, with the new question branch."],
  ];
  return <main className="max-w-4xl mx-auto px-5 py-10 space-y-7">
    <div className="flex items-center gap-4"><JJLogo className="h-12 w-12"/><div><h1 className="font-serif text-2xl font-semibold">A shorter reflection. The same care.</h1><p className="text-sm text-muted-foreground mt-2">Distant / Exploring review · 38 statements · 15 measured pathways</p></div></div>
    <p className="text-sm leading-relaxed max-w-2xl">Review the new survey branch and reports here before release. All examples are synthetic. Practice responses are discarded; this preview has no connection to production data, payments or email.</p>
    <div className="grid sm:grid-cols-2 gap-4">
      {options.map(([href, title, description]) => <Link key={href} href={href} className="rounded-lg border bg-card p-5 space-y-2 hover:border-primary block focus:outline-primary" data-testid={`review-${href.replaceAll("/", "-")}`}><h2 className="font-semibold text-base">{title}</h2><p className="text-sm text-muted-foreground leading-relaxed">{description}</p><span className="inline-block text-sm text-primary pt-2">Open review →</span></Link>)}
    </div>
    <section className="border-t pt-6 space-y-3">
      <h2 className="font-semibold text-base">Generated PDF examples</h2>
      <p className="text-sm text-muted-foreground">These files were generated by the application’s report engine using synthetic responses. Full-only church waves retain the existing report format; mixed waves use the separated-cohort format shown here.</p>
      <div className="flex flex-wrap gap-4 text-sm">
        {[["mixed-church", "Mixed church report"], ["mixed-comments", "Unlinked comments"], ["mixed-debrief", "Admin debrief"], ["short-only-church", "Short-only church report"], ["small-church", "Small-cohort suppression"]].map(([file, label]) => <a key={file} href={`./samples/${file}.pdf`} target="_blank" rel="noreferrer" className="underline underline-offset-4">{label}</a>)}
      </div>
    </section>
  </main>;
}
const report = buildCohortReporting(mixedRows);
const small = buildCohortReporting([makeSyntheticResponse(), ...Array.from({ length: 15 }, (_, i) => makeSyntheticResponse(false, i))]);
const debrief = buildDebriefingReport({ waveId: "synthetic", churchId: "synthetic", churchName: "Review Church (synthetic)", waveLabel: "Short-form review", rows: mixedRows });
function Review() {
  return <QueryClientProvider client={queryClient}><TooltipProvider><Router hook={useHashLocation}>
    <div className="border-b bg-primary/5 px-4 py-3 flex flex-wrap justify-between gap-3 text-sm print:hidden">
      <span><strong>Private review only.</strong> Synthetic data. Not the live survey.</span>
      <Link href="/" className="underline underline-offset-4">Review home</Link>
    </div>
    <Switch>
      <Route path="/survey" component={SurveyFlow}/>
      <Route path="/join/:code" component={JoinSurveyFlow}/>
      <Route path="/sample/distant">{() => <Sample initial={1}/>}</Route>
      <Route path="/sample/exploring">{() => <Sample initial={2}/>}</Route>
      <Route path="/sample/full">{() => <Sample initial={3}/>}</Route>
      <Route path="/group">{() => <main className="max-w-3xl mx-auto p-5"><CohortReportView report={report}/></main>}</Route>
      <Route path="/small">{() => <main className="max-w-3xl mx-auto p-5"><CohortReportView report={small}/></main>}</Route>
      <Route path="/debrief">{() => <main className="max-w-5xl mx-auto p-5"><DebriefingReportView report={debrief}/></main>}</Route>
      <Route component={Home}/>
    </Switch>
  </Router></TooltipProvider></QueryClientProvider>;
}
createRoot(document.getElementById("root")!).render(<Review/>);
