export interface PathwayDef {
  num: number;
  name: string;
  goal: string;
  tagline: string;
  scripture: string;
  items: string[];
  narrative: { high: string; medium: string; low: string };
}

export const ITEM_BULLETS: Record<string, string> = {
  K1: "God originally created the world to be good.",
  K2: "Human failures have broken our world, altering what God designed.",
  K3: "God will one day make everything new, as God intended it to be.",
  K4: "I can sometimes experience God's promised future in my life now.",
  K5: "I will not always experience God's healing in my life now.",
  B1: "God is loving, caring and active in my life, like a very good parent.",
  B2: "Jesus has provided a way for me to have a relationship with God forever.",
  B5: "Nothing can keep me from experiencing God's unconditional love if I turn to God.",
  T1: "There is nothing I can do to make God love me more or love me less.",
  B6: "The way God sees me is rooted in God's faithful love for me.",
  T2: "How I see myself is determined most of all by how I believe God sees me.",
  T4: "The things I do for Jesus I do not as an obligation but for the joy of serving.",
  B7: "The challenges of my life will be used by God to deepen my trust in God.",
  T5: "Even in hard times, I experience peace, trusting that God is with me.",
  T6: "In challenging situations, I first seek to know how God wants me to respond.",
  C1: "I am very aware of the active presence of God in all aspects of my life.",
  C2: "When I notice that I'm moving away from God, I quickly turn to be restored.",
  C3: "I expect God's Holy Spirit to guide me and give me power to live my life God's way.",
  T9: "I trust in and am committed to God's purposes for my life.",
  B3: "Knowing that honestly speaking to God is necessary for a healthy relationship with God.",
  B4: "Faithfully listening so God can speak to me in ways I can recognize.",
  C7: "Spending time every day speaking with God and seeking God's direction.",
  T8: "When having thoughts and actions that displease God, I quickly confess them.",
  C4: "Faithfully setting aside personal time to read/listen to the Bible.",
  C5: "Reviewing the writings and resources of other Christians to understand God better.",
  C8: "Engaging in spiritual practices such as fasting, meditation, silence, etc.",
  P6: "Regularly inviting God's leadership to be expressed in your life.",
  C6: "Regularly expressing praise for who God is in your life.",
  T7: "Regularly giving thanks to God for acting in your life.",
  A6: "Meeting weekly with other Christians to worship/pray/learn.",
  B8: "Loving others can make a difference in my relationship with God.",
  K8: "Loving others as Jesus has loved me furthers God's will in this world.",
  T3: "Others see my love for God in how I express my love for them.",
  L9: "In the various settings of my life, people see in me God's love being expressed.",
  P8: "God is forming me to be a gift of love and grace to others.",
  A1: "Allowing Jesus to change your behavior and the moral decisions you make.",
  A3: "Actively trying to listen & understand people in your relationship circle.",
  L7: "Being willing to share about Jesus when talking with others.",
  P1: "Trying to see people through God's eyes, not just your own.",
  P4: "Asking the Holy Spirit to reveal God's presence when you are praying or interacting.",
  A7: "Having people you can be honest with about your spiritual life and walk.",
  A8: "Forming close relationships to help people on their spiritual journey.",
  A9: "Welcoming the input of other Christians in your journey to be like Jesus.",
  P5: "Encouraging others to have confidence in God's active presence in their lives.",
  A4: "Pursuing reconciliation in relationships by seeking and giving forgiveness.",
  L2: "Not requiring that people change in order for you to forgive them.",
  L3: "Working toward forgiving others just as God forgives you.",
  B9: "Desiring to have God participate in all relationships that are in your life.",
  K6: "Seeing yourself as a partner with God in helping make the earth new again.",
  K7: "Knowing that the Holy Spirit can guide you to fulfill God's desires for this world.",
  L8: "Allowing the Holy Spirit to help you apply God's wisdom to all your life situations.",
  P3: "Fully knowing you are partnering with God in your interactions with people.",
  C9: "Asking God for wisdom to use the resources God has given you.",
  A2: "Seeking to know how God wants you to use your gifts and abilities.",
  A5: "Gladly using your resources to help others experience Jesus' love & invitation.",
  L4: "Being glad and willing to give generously to people who are in need.",
  L1: "Showing care to people just as they are, as Jesus has done for you.",
  P2: "Finding it easy to respond to others as God does, with kindness and compassion.",
  P9: "Having confidence that God will give you grace to help people with healing or needed change.",
  P7: "In situations of need that you see, acting boldly upon what you believe God desires to do.",
  K9: "Believing that serving the poor and oppressed is part of God's plan to restore justice in the world.",
  L5: "Noticing people who are not always accepted and forming relationships with them.",
  L6: "Taking practical actions against oppression and injustice.",
};

export const PATHWAYS: PathwayDef[] = [
  {
    num: 1,
    name: "Believing God's Story",
    goal: "Trusting Jesus",
    tagline: "How much do I believe in God's good plans for all of creation",
    scripture: "Jeremiah 29:11",
    items: ["K1", "K2", "K3", "K4", "K5"],
    narrative: {
      high: "You demonstrate a strong grasp of the Story into which God has invited us to be a part. Your understanding can be a stable foundation from which to engage in the adventures that come as you follow God. Your beliefs are particularly anchored by your agreement with the following statements",
      medium: "While you have a solid grasp of the story of God's great invitation, there are still some elements that could build an even more secure foundation for you. As you continue to dig deeper into God's good plans for you and this world, your mind and heart will faithfully guide you in your journey toward Jesus. In particular, it would be helpful to further explore the following",
      low: "There is much about the story of God's great invitation that you have not yet had the opportunity to know and embrace fully. As you discover more of God's good plans for you and this world, much more of the journey you are on will make sense to your mind and heart. In particular, it would be very helpful to explore further the following beliefs",
    },
  },
  {
    num: 2,
    name: "Receiving God's Love",
    goal: "Trusting Jesus",
    tagline: "How much do I believe that God actively loves and cares for me?",
    scripture: "John 15:9-13",
    items: ["B1", "B2", "B5", "T1"],
    narrative: {
      high: "You demonstrate confidence that God is loving and caring and wants the best for you. You are secure in knowing that nothing can separate you from God if you choose to respond to the Holy Spirit's invitations. Your agreement with the following statements indicates particular strengths in your life in this area",
      medium: "While you are aware of God's unconditional love for you, you have not yet taken the opportunity to trust in it more fully. As you do, a new level of peace and rest will be unlocked in your life. As you continue to see more and more how God is like Jesus, any continuing fear will be replaced by anticipation. Ask Jesus to further establish these beliefs as anchors in your life",
      low: "Coming to know and trust in God's unconditional love for you more fully will unlock a whole new level of peace and rest in your life. As you see more and more the true character of God, any fear will be replaced by anticipation. Ask God to set these beliefs as anchors in your life",
    },
  },
  {
    num: 3,
    name: "My Identity",
    goal: "Trusting Jesus",
    tagline: "How secure is my identity in God's good intentions for me?",
    scripture: "1 John 3:1",
    items: ["B6", "T2", "T4"],
    narrative: {
      high: "You demonstrate that God's heart for you is filled with hope and invitation. This affects and is forming the way you view yourself and is increasingly freeing you to follow Jesus with joy and gratitude. This strength in your life is reflected in the following characteristics",
      medium: "God wants to show you even more fully how love is the only lens through which God sees you. As the security of knowing how God sees you continues to grow in you, you will have much greater confidence to reach toward God and live like Jesus did. As you keep growing in this new way of seeing, your experience of freedom will keep increasing as well. Consider the following statements, which reflect God's invitation",
      low: "God wants to show you more fully how love is the lens through which He sees you. The security of knowing how God sees you will give you much greater confidence to reach toward God and follow the teachings of Jesus. God is inviting you toward this new way of seeing and the freedom that it will bring. Consider the following statements, which reflect His invitation",
    },
  },
  {
    num: 4,
    name: "Facing Challenges",
    goal: "Trusting Jesus",
    tagline: "How able am I to experience God's peace even when challenges come my way?",
    scripture: "Philippians 4:6",
    items: ["B7", "T5", "T6"],
    narrative: {
      high: "In spite of challenging and difficult experiences in your life, your trust in God is not shaken. You have confidence that nothing will be able to separate you from God's love and good plans for you. Your alignment with the following statements expresses that reality",
      medium: "You're being invited to know more deeply that God is for you – even when everything seems to be against you. You have an opportunity to learn to trust God more fully and consistently in the middle of adversity and to have a deeper experience of the peace that comes from that trust. Ask God's Holy Spirit to help you in your journey of trusting God even more, and explore how the following statements could become even more real for you",
      low: "You are invited to know more deeply that God is for you - even when everything seems to be against you. You have an opportunity to discover how to trust God in the middle of adversity and to experience the deep peace that comes from that trust. Ask God's Spirit to help you in your journey of trusting God more, and explore how the following statements could become real for you",
    },
  },
  {
    num: 5,
    name: "Responding to God",
    goal: "Experiencing Jesus",
    tagline: "How aware and open am I to being guided by God in my day-to-day life?",
    scripture: "Romans 12:1-2",
    items: ["C1", "C2", "C3", "T9"],
    narrative: {
      high: "You are responsive to the Holy Spirit guiding you to live your life in a way that pleases God. You actively look to God for direction and are careful to embrace it. The following statements reflect particular strengths in your sensitivity to God",
      medium: "Your relationship with God can be even more active and alive than you are experiencing at this time. The next step in your journey could involve a more intimate sensitivity to God's presence and direction. Explore how you can grow in these dimensions of your relationship with God",
      low: "God is inviting you to discover just how much more active and alive your relationship with the God's Spirit can be. The next step in your journey could involve a more intimate sensitivity to God's presence and direction. Explore how you can grow in these dimensions of your relationship with God",
    },
  },
  {
    num: 6,
    name: "Communicating with God",
    goal: "Experiencing Jesus",
    tagline: "How often do I pray and seek God's guidance for my life?",
    scripture: "1 Thessalonians 5:17-18",
    items: ["B3", "B4", "C7", "T8"],
    narrative: {
      high: "You purposefully spend time both speaking and listening to God. This healthy practice of communication keeps your relationship with Jesus alive and vibrant and helps you to stay close to God's desires for you. Some keys to this strength are found in your commitment to these things",
      medium: "You are fully aware that intentional and consistent communication is essential in your relationship with God. By developing some new positive habits, you can further translate this belief into a more frequent and rich dialogue with God. Explore with God and others how you could grow in these practices",
      low: "Just as in any meaningful relationship, intentional and consistent communication is essential in our relationship with God. You have a great opportunity to develop a more frequent and rich dialogue with God by developing some new positive habits. Explore with God and others how you could grow in these practices",
    },
  },
  {
    num: 7,
    name: "Growing my Faith",
    goal: "Experiencing Jesus",
    tagline: "How faithful am I in setting aside time to develop practices that draw my close to God?",
    scripture: "1 Timothy 4:8",
    items: ["C4", "C5", "C8", "P6"],
    narrative: {
      high: "You are not passive in your approach to relationship with God. As God invites you into the journey of Jesus you deliberately engage with that invitation through tangible actions. Examples of such activities are",
      medium: "As you know, Christians through the ages have discovered that there are specific things we can do to receive and encourage the grace of God working in us. Embracing more fully some of these historic practices could make a difference in the vibrancy of your relationship with God",
      low: "Christians through the ages have discovered that there are specific things we can do to receive and encourage the grace of God working in us. Embracing more of these historic practices could make a big difference in the vibrancy of your relationship with God",
    },
  },
  {
    num: 8,
    name: "Worshipping",
    goal: "Experiencing Jesus",
    tagline: "How often do I express praise and thankfulness to God for acting in my life?",
    scripture: "Psalms 86:12",
    items: ["C6", "T7", "A6"],
    narrative: {
      high: "Worship is a strength in your life with God. You are intentional and consistent in expressing your appreciation for who God is and what God does in your life. This strength shows itself in your faithfulness to these practices",
      medium: "Though expressing back to God both gratitude and respect is important to you, there is potential for growth in your practice of worship both alone and together with others. Consider how you might grow by more often engaging in these simple activities",
      low: "Something powerful happens in us when we express back to God both gratitude and respect using real words and songs. It is particularly strengthening when we do this with others. Consider how you might grow by more often engaging in these simple activities",
    },
  },
  {
    num: 9,
    name: "Expressing God's Love",
    goal: "Expressing Jesus",
    tagline: "How able are others to see God's love in the way I act toward them?",
    scripture: "John 13:34-35",
    items: ["B8", "K8", "T3", "L9", "P8"],
    narrative: {
      high: "God's love is not simply an abstract concept for you. You freely share the love of Jesus in tangible ways with others in your life and see that activity as a central part of your calling in the world. This call to love is expressed in your agreement that these statements are true in your life at this time",
      medium: "You are certainly aware that showing love to others just as God has shown love to us produces a refreshing flow of God's goodness in and through us. There is yet opportunity for growth in the ways you let love direct how you relate to others around you. Pray about and discuss with your friends how you might continue to mature in understanding God's love and expressing it in these ways",
      low: "Showing love to others just as God has shown love to us produces a refreshing flow of God's goodness in and through us. Consider how God wants you to grow in letting love direct how you relate to others around you. Pray about and discuss with your friends how you might increasingly understand God's love and express it in these ways",
    },
  },
  {
    num: 10,
    name: "Practicing my Faith",
    goal: "Expressing Jesus",
    tagline: "Is my day-to-day life one where my choices are aligned with God's will?",
    scripture: "Ephesians 4:32",
    items: ["A1", "A3", "L7", "P1", "P4"],
    narrative: {
      high: "Following Jesus is making a real difference in your life and you are seeking to imitate Jesus in the way you respond to others around you, the way you see them, listen to them and act toward them. This is shown clearly in the way you commit yourself to the following",
      medium: "You are serious about trusting God enough to show you how to really live. You now have a wonderful opportunity to let God direct you more fully in what you say and do. Seeking to make the following statements more true and more deeply rooted in your life will help you walk out that trust",
      low: "Following God means trusting God enough to show us how to live fully. There is a wonderful opportunity ahead of you to discover how to relate to people around you in new ways - letting God direct you in what you say and do. Seeking to make the following statements true and deeply rooted in your life will help you walk out that trust",
    },
  },
  {
    num: 11,
    name: "Journeying with Others",
    goal: "Expressing Jesus",
    tagline: "Am I connected with and connecting others on my journey with God?",
    scripture: "Hebrews 10:24-25",
    items: ["A7", "A8", "A9", "P5"],
    narrative: {
      high: "You are not trying to follow God alone. You are embracing the wisdom and strength that other followers of Jesus can bring along the way. Your particular strengths in these reciprocal relationships are",
      medium: "As you are very aware, following God is a team game. We grow best as Christians when we walk it out together. You have a wonderful opportunity to continue to discover and grow in that strength as you reach out to others in the following ways",
      low: "Following God is a team game. We grow best on our spiritual journey when we walk it out together. You have a wonderful opportunity to discover and grow in that strength as you reach out to others in the following ways",
    },
  },
  {
    num: 12,
    name: "Reconciling",
    goal: "Expressing Jesus",
    tagline: "How able am I to be a forgiving and reconciling person?",
    scripture: "Colossians 3:13",
    items: ["A4", "L2", "L3"],
    narrative: {
      high: "Understanding the reconciling heart of God is a strength of your journey with Jesus. You are committed to the process of forgiveness that Jesus modeled. The following illustrates how you follow that example",
      medium: "Just as God has been diligent in inviting you to be fully reconciled with God, God also wants you to keep on growing in the freedom that walking in forgiveness can bring. Continuing to grow in your ability to forgive and be forgiven will have an ongoing transformative impact on your life. Look for the invitation of God to make these things a great strength in your life and walk",
      low: "Just as God has been diligent in inviting you to be fully reconciled with God, God also wants you to discover and experience the freedom that walking in forgiveness can bring. Growing in your ability to forgive and be forgiven will have a transformative impact on your life. Look for the invitation of God to make these things a present reality for you",
    },
  },
  {
    num: 13,
    name: "Partnering with God",
    goal: "Serving Jesus",
    tagline: "How aware am I of God's presence in my relationships with others?",
    scripture: "Colossians 3:12",
    items: ["B9", "K6", "K7", "L8", "P3"],
    narrative: {
      high: "You understand that following Jesus is lived out through a day by day, moment by moment partnership with the Holy Spirit. You are aware of this interaction in the various relationships and situations that you encounter along your journey. The following ways in which you embrace these beliefs and actions support this strength",
      medium: "Part of your joy in discovering God has been realizing how serious God is about actively partnering with us to see this world made right. God is inviting you to expand your expectation and your experience of partnering with the Holy Spirit to make a greater difference all around you every day. Explore how you could grow in these areas",
      low: "Part of the joy in discovering God is realizing how serious God is about actively partnering with us to see this world made right. God is inviting you to expand your expectation and your experience of partnering with the Holy Spirit to make a real difference all around you each day. Explore how you could grow in these areas",
    },
  },
  {
    num: 14,
    name: "Stewarding Resources",
    goal: "Serving Jesus",
    tagline: "How much do I see what I have as fully mine or as a gift to use for God's purposes?",
    scripture: "Matthew 6:19-24",
    items: ["C9", "A2", "A5", "L4"],
    narrative: {
      high: "You see your time, energy and money as gifts of God to be used under God's direction. You find joy in expressing the generosity of Jesus with your abilities and resources. This is how you indicated that you now express your trust in God in this area of the journey",
      medium: "You have an opportunity to trust yet even more in God's overflowing generosity toward you by seeing yourself less as an owner and more as a steward of God's resources. You are invited now to experience more of the joy of generosity flowing through your life to others. Consider how you might step into an even greater depth of trusting God in the following areas",
      low: "You have an opportunity to trust God's overflowing generosity toward you by seeing yourself less as an owner and more as a steward of God's resources. You are invited now to discover the joy of experiencing generosity flow through your life to others. Consider how you might step forward and trust God more in the following areas",
    },
  },
  {
    num: 15,
    name: "Showing Compassion",
    goal: "Serving Jesus",
    tagline: "Do I see the needs of others and respond with Godly kindness and grace?",
    scripture: "James 2:14-18",
    items: ["L1", "P2", "P9", "P7"],
    narrative: {
      high: "You respond faithfully to God's heart of compassion for those around you. Your understanding of what Jesus has done for you moves you to extend his mercy in active ways to others. Your trust in Jesus' compassion is particularly demonstrated through these actions",
      medium: "You have seen in your life that the more we experience the love of Jesus for us, the more we are moved by that love to care about the things that God cares about. God is near you, stirring your heart to let love take you into still new activities and directions. You have a wonderful opportunity to let God's compassion in you further impact the lives of those in need around you. Consider how you might continue to grow in these areas",
      low: "The more we experience the love of God for us, the more we are moved by that love to care about the things that God cares about. Very likely God is stirring your heart to let love take you into new activities and directions. You have a wonderful opportunity to let God's compassion in you impact the lives of those in need around you. Consider how you could grow in these areas",
    },
  },
  {
    num: 16,
    name: "Acting Justly",
    goal: "Serving Jesus",
    tagline: "How sensitive am I to community and personal injustices and discrimination?",
    scripture: "Luke 10:30-37",
    items: ["K9", "L5", "L6"],
    narrative: {
      high: "For you, the call to follow Jesus is a commitment to helping restore God's justice to this world. You are discovering how that is walked out in real ways through your life. You show this commitment in the following ways",
      medium: "You are convinced that at the center of God's story is the promise to put everything right again. And you know that means restoring the lives of real people who are victims of oppression and evil. Pray about how your heart can be captured even more by the things God's heart cares about. Look for ways you can grow in your understanding of God's heart for justice, and more particularly your participation in pursuing it",
      low: "At the center of God's story is the promise to put everything right again. Of course, that means restoring the lives of real people who are victims of oppression and evil. Pray about how your heart can be captured further by what God's heart cares about. Look for ways you can grow in your understanding of God's heart for justice, and your participation in pursuing it",
    },
  },
];

export const GOALS = ["Trusting Jesus", "Experiencing Jesus", "Expressing Jesus", "Serving Jesus"];