export interface SurveyItem {
  code: string;
  text: string;
}

export const SURVEY_ITEMS: SurveyItem[] = [
  { code: "B1", text: "I believe God is loving, caring and active in my life, like a very good parent would be." },
  { code: "B2", text: "I believe Jesus has provided a way for me to have a relationship with God forever." },
  { code: "B3", text: "I believe that openly and honestly speaking to God is necessary for a healthy relationship with God." },
  { code: "B4", text: "I believe God regularly communicates with me in ways I can recognize." },
  { code: "B5", text: "I believe nothing can keep me from experiencing God's unconditional love -- even my own sin - if I turn to God." },
  { code: "B6", text: "I believe the way God sees me is rooted in God's faithful love for me." },
  { code: "B7", text: "I believe the challenging circumstances of my life will be used by God to deepen my trust in God's care for me." },
  { code: "B8", text: "I believe loving others can make a difference in my relationship with God." },
  { code: "B9", text: "I believe that God desires to be actively involved in all the relationships that are part of my life." },
  { code: "K1", text: "I believe God originally created the world to be good." },
  { code: "K2", text: "I believe human failures have caused our world to be broken, altering what God designed." },
  { code: "K3", text: "I believe God will one day make everything new, as God intended it to be." },
  { code: "K4", text: "I believe I can sometimes have experiences of God's promised future in my everyday life now." },
  { code: "K5", text: "I believe I will not always experience God's healing in every circumstance of my life now." },
  { code: "K6", text: "I see myself as an active partner with God in helping to restore God's desires to make the earth new again." },
  { code: "K7", text: "I believe God's Holy Spirit can guide my actions to fulfill God's desires for this world in which we live." },
  { code: "K8", text: "I believe loving others as Jesus has loved me is one of the most important things I can do to further God's will in this world." },
  { code: "K9", text: "I believe serving the poor and oppressed is an essential part of God's plan to restore God's justice in the world." },
  { code: "A1", text: "Following God has changed my behavior, affecting how I speak, the places I go, and the moral decisions I make." },
  { code: "A2", text: "I seek to know how God wants me to use my gifts and abilities." },
  { code: "A3", text: "I actively try to listen and understand everyone with whom I have a relationship." },
  { code: "A4", text: "I work toward pursuing reconciliation in any broken relationships by both requesting and giving forgiveness." },
  { code: "A5", text: "I gladly use my resources (home, money, time) to help others experience the love and invitation of Jesus." },
  { code: "A6", text: "I meet together weekly with other Christians to worship/pray/learn." },
  { code: "A7", text: "I have people I trust with whom I can be honest about the state of my spiritual life and walk." },
  { code: "A8", text: "I have formed some close relationships through which I try to help people on their spiritual journey." },
  { code: "A9", text: "I welcome the practical wisdom and input of other Christians in my journey to become more like Jesus." },
  { code: "L1", text: "I show kindness and care for the needs of people just as they are, as God has done for me." },
  { code: "L2", text: "I do not require that people change for me to forgive them." },
  { code: "L3", text: "I work toward forgiving others who have wronged me just as God forgives me." },
  { code: "L4", text: "I am gladly willing to give generously to people who are in need." },
  { code: "L5", text: "I take notice of people who are not always accepted and form relationships with them." },
  { code: "L6", text: "I take practical actions against oppression and injustice." },
  { code: "L7", text: "I am willing to share about my life with God when talking with others." },
  { code: "L8", text: "The Holy Spirit helps me apply God's wisdom to specific life situations that I see or experience." },
  { code: "L9", text: "In the various settings of my life (e.g. work, home, with friends, etc.), people see in me God's love being expressed." },
  { code: "P1", text: "I try to focus on seeing people around me through God's eyes, not just my own." },
  { code: "P2", text: "I find it easy to respond to others as God does - with kindness and compassion." },
  { code: "P3", text: "I am fully aware that I am partnering with God in my interactions with people." },
  { code: "P4", text: "I ask the Holy Spirit to reveal God's presence to people with whom I am praying or interacting." },
  { code: "P5", text: "I encourage other followers of Jesus to believe and have confidence in God's active presence in their lives." },
  { code: "P6", text: "I regularly invite God's leadership to be expressed in my life." },
  { code: "P7", text: "In situations of need that I see or hear, I act boldly upon what I believe God desires to do." },
  { code: "P8", text: "I see God actively forming me to be a gift of love and grace to others." },
  { code: "P9", text: "When I reach out to people in need, I have confidence that God will give me grace to help them toward healing, deliverance, and change." },
  { code: "C1", text: "I am very aware of the active presence of God in all aspects of my life." },
  { code: "C2", text: "When I notice that I am moving away from God, I quickly turn toward God to be restored." },
  { code: "C3", text: "I expect God's Holy Spirit to guide me and give me the power to live my life God's way." },
  { code: "C4", text: "I faithfully set aside personal time to read from or listen to the Bible." },
  { code: "C5", text: "I read, listen, or view the writings and/or media of other Christians for help in understanding God better." },
  { code: "C6", text: "I take time to regularly express praise for who God is in my life." },
  { code: "C7", text: "I spend time every day speaking with God and seeking God's thoughts and direction." },
  { code: "C8", text: "To support God's grace working in my life, I engage in spiritual practices such as fasting, meditation, or silence, etc." },
  { code: "C9", text: "I ask God for wisdom in how to use the resources God has given me (time, energy and money)." },
  { code: "T1", text: "I know there is nothing I can do to make God love me more or love me less." },
  { code: "T2", text: "The way I see myself is determined most of all by how I believe God sees me." },
  { code: "T3", text: "Others see my love for God in how I express my love for them." },
  { code: "T4", text: "The things I do for God I do for the joy of serving, not as a duty or obligation." },
  { code: "T5", text: "Even in hard or difficult times, I am able to experience a deep sense of peace, trusting that God is with me." },
  { code: "T6", text: "When I face challenging situations, I first seek to know how God would want me to respond." },
  { code: "T7", text: "I am a person who regularly gives thanks to God for acting in my life." },
  { code: "T8", text: "When I notice I have thoughts, motivations, words and actions that are displeasing to God, I am quick to confess them." },
  { code: "T9", text: "I trust in and am committed to God's purposes for my life." },
];